#!/bin/sh

set -ex

## Get the directory for the script.
dirname=$(dirname "$0")

## Write the package version to an external file.
>"$dirname/VERSION" awk \
         '$1==";;" && $2=="Version:" { print $3; exit }' \
         "$dirname/kixtart-mode.el"
test -s "$dirname/VERSION"

## Initialize build system.
autoreconf --install "$dirname"
